---
- hosts: localhost
  name: Install dotnet
  become: true
  become_user: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: Download installer
      ansible.builtin.get_url:
        url: https://dot.net/v1/dotnet-install.sh
        dest: /tmp/dotnet-install.sh
        mode: '0755'
        force: 'yes'

    - name: Install dotnet 6.0
      register: exists_6
      changed_when: "'is already installed' not in exists_6.stdout"
      ansible.builtin.command: /tmp/dotnet-install.sh --channel 6.0 --version latest

    - name: Install dotnet 7.0
      register: exists_7
      changed_when: "'is already installed' not in exists_7.stdout"
      ansible.builtin.command: /tmp/dotnet-install.sh --channel 7.0 --version latest

    - name: Install dotnet 8.0
      register: exists_8
      changed_when: "'is already installed' not in exists_8.stdout"
      ansible.builtin.command: /tmp/dotnet-install.sh --channel 8.0 --version latest

    - name: Add .dotnet to path
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: "export PATH=\"$PATH:{{ lookup('env', 'HOME') }}/.dotnet\""
        state: present
        insertafter: EOF

    - name: Add .dotnet/tools to path
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: "export PATH=\"$PATH:{{ lookup('env', 'HOME') }}/.dotnet/tools\""
        state: present
        insertafter: EOF

    - name: Add DOTNET_ROOT
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.bashrc"
        line: "export DOTNET_ROOT=\"{{ lookup('env', 'HOME') }}/.dotnet\""
        state: present
        insertafter: EOF
